const option = (value, label, axis, score) => ({ value, label, scores: { [axis]: score } });
const scale = (id, prompt, axis, labels) => ({id, prompt, type:"choice", options:[option("a",labels[0],axis,-2),option("b",labels[1],axis,-1),option("c",labels[2],axis,1),option("d",labels[3],axis,2)]});
const outcomes = (low, middle, high) => [
  {at:20,title:low[0],description:low[1],insight:low[2]},
  {at:50,title:middle[0],description:middle[1],insight:middle[2]},
  {at:80,title:high[0],description:high[1],insight:high[2]},
];

export const QUIZZES = [
  {id:"social-battery",glyph:"☀",color:"#df6c59",minutes:3,title:"What charges your social battery?",description:"Discover how you connect, recharge, and find your people.",axes:[{id:"social",left:"Solitude",right:"Togetherness"}],questions:[
    scale("party","You arrive at a party where you know one person. What happens next?","social",["I find a quiet corner","I stick with my person","I meet a few new faces","I work the whole room"]),
    scale("weekend","Your ideal unplanned Saturday looks like…","social",["A glorious day alone","One close friend and no agenda","A loose group plan","Everyone I know, somewhere loud"]),
    scale("call","A friend calls without texting first.","social",["I watch it ring","I text back","I answer if I have energy","I answer—finally, a plot twist"]),
    scale("recover","After a crowded week, you recover by…","social",["Going fully off-grid","Keeping company very small","Mixing quiet time and plans","Planning something even bigger"]),
    scale("news","When something wonderful happens, you…","social",["Keep it close for a while","Tell one trusted person","Share it with your circle","Broadcast it immediately"]),
  ],outcomes:outcomes(["The Quiet Current","You connect deeply and protect your energy with intention.","Your solitude is not an absence—it is where your inner world gets its color."],["The Selective Spark","You move easily between company and quiet, choosing each on purpose.","You don't need every room. You just know which rooms feel like home."],["The Human Sunbeam","Connection wakes you up. You make energy by passing it around.","You leave people a little warmer than you found them."])},
  {id:"decision-style",glyph:"⌁",color:"#bd7aa0",minutes:4,title:"How do you make a hard choice?",description:"Meet the inner voice that takes the wheel when the path splits.",axes:[{id:"choice",left:"Instinct",right:"Analysis"}],questions:[
    scale("menu","A menu has twelve excellent choices. You…","choice",["Pick the first thing that sings","Choose in under a minute","Compare my top three","Research before I arrive"]),scale("risk","A promising opportunity has one big unknown.","choice",["Leap; clarity follows motion","Check my gut, then move","Make a pros-and-cons list","Wait until I can model the risk"]),scale("advice","When friends give conflicting advice, you…","choice",["Trust the answer already in me","Notice which advice feels lighter","Look for the strongest evidence","Build a decision framework"]),scale("mistake","After a choice goes badly, you…","choice",["Accept it and redirect","Reflect, but don't dwell","Trace what I missed","Rewrite the whole process"]),scale("clock","A deadline is approaching.","choice",["Pressure sharpens my instinct","I decide and adjust later","I use every useful minute","I ask for more information"])
  ],outcomes:outcomes(["The Compass","Your instincts notice patterns before language catches up.","You don't always explain the path, but you can feel when it is yours."],["The Navigator","You let evidence and intuition keep each other honest.","Your best decisions happen where a clear head meets a quiet yes."],["The Cartographer","You create clarity by mapping what others leave hazy.","For you, understanding isn't delay—it is how courage gets built."])},
  {id:"creative-weather",glyph:"✦",color:"#d49b45",minutes:3,title:"What's your creative weather?",description:"Find the conditions where your most original ideas tend to appear.",axes:[{id:"create",left:"Structure",right:"Spontaneity"}],questions:[scale("blank","A blank page feels like…","create",["A request for a plan","A space needing a prompt","An open door","A dare I cannot resist"]),scale("routine","Your creative routine is…","create",["Sacred and scheduled","A few reliable rituals","Different every week","Beautifully nonexistent"]),scale("stuck","When stuck, you…","create",["Break the task into steps","Add a constraint","Change rooms or mediums","Follow a completely new idea"]),scale("finish","Finishing is easiest when…","create",["The brief is precise","There is a real deadline","Someone is waiting to see it","I am still surprised by it"]),scale("ideas","Your best ideas arrive…","create",["During focused work","After gathering references","While doing something else","At the least convenient moment"]),],outcomes:outcomes(["The Greenhouse","Your imagination flourishes inside lovingly built structures.","Constraint is not a cage for you. It is a trellis."],["The Changing Sky","You create through a balance of ritual and surprise.","You know when to make a plan—and when to let the weather change it."],["The Lightning Field","Ideas find you in motion, alive to accidents and unlikely links.","Your gift is catching the spark before the world talks you out of it."])},
  {id:"conflict-language",glyph:"❋",color:"#678d7a",minutes:4,title:"What's your conflict language?",description:"See how you protect connection when things get uncomfortable.",axes:[{id:"conflict",left:"Harmony",right:"Directness"}],questions:[scale("late","A friend is repeatedly late.","conflict",["Let it go","Hint that it bothers me","Name it gently","Address it the next time it happens"]),scale("tone","A message sounds unexpectedly sharp.","conflict",["Assume they had a bad day","Wait and observe","Ask what they meant","Say how it landed immediately"]),scale("group","Your group cannot agree.","conflict",["Help everyone feel heard","Find common ground","Call for a vote","Argue for the strongest option"]),scale("apology","The best apology begins with…","conflict",["Reassurance","Understanding impact","Clear accountability","Naming exactly what went wrong"]),scale("tension","Unspoken tension in a room makes you…","conflict",["Try to soften the mood","Check in privately","Bring it into the open","Feel relieved someone finally noticed"]),],outcomes:outcomes(["The Bridgekeeper","You protect the relationship while others protect their position.","Your softness is skilled work—just remember your truth deserves a seat too."],["The Clear Harbor","You pair honesty with care and make difficult truths feel survivable.","People trust you because your candor still leaves the door open."],["The Bell Ringer","You would rather meet the real issue than live beside its shadow.","Your directness clears the air; kindness helps everyone breathe it."])},
  {id:"curiosity",glyph:"◒",color:"#697fa8",minutes:3,title:"Where does your curiosity lead?",description:"Map the questions your mind cannot resist following.",axes:[{id:"curious",left:"Depth",right:"Breadth"}],questions:[scale("book","At a bookstore, you…","curious",["Find three books on one obsession","Stay in a favorite section","Browse whatever catches my eye","Leave with five unrelated subjects"]),scale("rabbit","Your internet rabbit holes are…","curious",["Deep enough to need equipment","Usually one topic at a time","A chain of surprising links","A pinball machine"]),scale("expert","You would rather become…","curious",["A world expert","Highly skilled in a niche","Conversant in many things","A permanent beginner"]),scale("question","A good answer makes you…","curious",["Ask a more precise question","Test the idea further","Connect it to something else","Open six new tabs"]),scale("museum","In a museum you…","curious",["Read every label in one room","Follow a curated path","Wander by instinct","Try to see absolutely everything"]),],outcomes:outcomes(["The Deep Diver","You stay with a question long enough for it to reveal another world.","Attention is your superpower; where you look deeply, things open."],["The Constellation Maker","You alternate between burrowing down and drawing connections outward.","You collect both roots and stars, then notice how they rhyme."],["The Wild Index","Your mind builds a joyful library of seemingly unrelated wonders.","What looks scattered to others is a constellation waiting for your line."])},
  {id:"rest",glyph:"☾",color:"#8674a3",minutes:3,title:"What kind of rest do you need?",description:"Not all tired is the same. Find what actually restores you.",axes:[{id:"rest",left:"Stillness",right:"Stimulation"}],questions:[scale("evening","A restorative evening includes…","rest",["Silence and an early bed","A bath, book, or slow walk","A favorite movie with someone","A lively change of scene"]),scale("vacation","Your body hears “vacation” and imagines…","rest",["A hammock","A cabin with a small itinerary","A new city at an easy pace","An adventure packed with novelty"]),scale("break","A ten-minute break is best spent…","rest",["Eyes closed","Making tea","Calling a friend","Walking somewhere new"]),scale("overwhelm","When overwhelmed, you crave…","rest",["Less of everything","Familiar comforts","A gentle distraction","A total pattern interrupt"]),scale("return","You know you are rested when…","rest",["My nervous system feels quiet","Small tasks feel possible","I want to connect again","I feel hungry for the world"]),],outcomes:outcomes(["The Soft Landing","Your system restores through quiet, safety, and fewer inputs.","Rest is not a reward. It is the ground returning beneath your feet."],["The Gentle Reset","You need a little comfort and a little movement to come home to yourself.","Rest works best when it is neither escape nor effort, but a kind return."],["The Fresh Horizon","Novelty and motion shake loose what routine has made heavy.","Sometimes rest is not stopping—it is remembering you are alive."])},
  {id:"inner-narrator",glyph:"“ ”",color:"#b56a58",minutes:5,title:"Meet your inner narrator",description:"Write a little. We'll read the themes in how you talk to yourself.",axes:[{id:"voice",left:"Tender",right:"Demanding"}],questions:[
    {id:"mistake",type:"text",prompt:"You made a small mistake that nobody else noticed. What do you say to yourself?",hint:"A sentence or two is plenty.",rubric:{voice:{keywords:["should","stupid","again","better","failure","careless","unacceptable"],score:2}},grading:{axis:"voice",scale:[-2,2],
      criteria:"How does the writer speak to themselves after a small mistake? Tender: compassionate, forgiving, keeps perspective, treats it as human. Demanding: harsh, self-critical, catastrophizing, perfectionistic, insulting themselves.",
      anchors:[
        {text:"Hey, it happens. Nobody even noticed, and now I know for next time.",score:-2},
        {text:"Oops. I'll quietly fix it and move on.",score:-1},
        {text:"Noted. I need to be more careful next time.",score:1},
        {text:"That was so stupid of me. I always do this and it's unacceptable.",score:2},
      ]}},
    {id:"proud",type:"text",prompt:"Finish this sentence: “I am quietly proud that I…”",rubric:{voice:{keywords:["tried","learned","kind","grew","survived","rested","asked"],score:-2}},grading:{axis:"voice",scale:[-2,2],
      criteria:"What is the writer proud of? Tender: proud of growth, effort, kindness, rest, surviving, asking for help — process over outcome. Demanding: proud only of output, flawless performance, outworking others, never slipping.",
      anchors:[
        {text:"kept going through a hard year and finally asked for help.",score:-2},
        {text:"learned to enjoy my own company.",score:-1},
        {text:"shipped a big project this year.",score:1},
        {text:"never missed a single deadline, even when I was exhausted.",score:2},
      ]}},
    {id:"friend",prompt:"Your closest friend makes the same mistake. Your response is…",type:"choice",options:[option("a","Warm, immediate reassurance","voice",-2),option("b","A gentle reality check","voice",-1),option("c","Practical advice for next time","voice",1),option("d","A firm push to do better","voice",2)]},
    scale("goal","When you reach a difficult goal, you tend to…","voice",["Celebrate how far I came","Let myself enjoy it","Quickly set the next target","Focus on what could have been better"])
  ],outcomes:outcomes(["The Inner Gardener","Your self-talk makes room for growth without demanding perfection.","The voice that helps you bloom sounds more like patience than pressure."],["The Honest Companion","Your inner voice can encourage and challenge you in equal measure.","You are learning that accountability does not have to abandon tenderness."],["The Relentless Coach","Your standards propel you, but their volume can hide how far you have come.","You deserve to be spoken to like someone worth helping, not fixing."])},
  {id:"change",glyph:"↝",color:"#6f9264",minutes:4,title:"How do you meet change?",description:"Find your natural rhythm when life redraws the map.",axes:[{id:"change",left:"Rooted",right:"Adaptive"}],questions:[scale("plans","Plans change at the last minute.","change",["I need a moment","I adjust reluctantly","I find a new plan","I enjoy the surprise"]),scale("move","In a new place, you first…","change",["Rebuild familiar routines","Find a few anchors","Explore the neighborhood","Try to become a local by Tuesday"]),scale("tool","A tool you know gets redesigned.","change",["Why fix what worked?","I wait for a guide","I click around","I hunt for every new feature"]),scale("chapter","When a life chapter ends, you…","change",["Honor it for a long time","Carry the best parts forward","Start sketching what is next","Feel the electricity of possibility"]),scale("identity","Changing your mind feels like…","change",["Losing solid ground","Something requiring good reason","Evidence that I am learning","One of life's best freedoms"]),],outcomes:outcomes(["The Old Oak","You meet change from a strong center built of meaning and continuity.","Your roots are wisdom, not resistance—so long as they still let you sway."],["The Tidal Tree","You keep what matters and let the form around it evolve.","Your steadiness travels with you; home is something you know how to remake."],["The Open Sail","Change activates your imagination and turns uncertainty into horizon.","You do not need the whole map when the wind is already teaching you."])},
];
